package web

const homeTemplate = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{.Title}}</title>
<style>
:root{color-scheme:light;background:#f5f1e8;color:#26352f;font-family:Georgia,"Noto Serif SC",serif}*{box-sizing:border-box}body{margin:0;line-height:1.7}header{background:#203a35;color:#f5f1e8;padding:24px 6vw;position:sticky;top:0;z-index:2}nav{display:flex;gap:24px;align-items:center;flex-wrap:wrap}nav a{color:#f5f1e8;text-decoration:none}nav details{position:relative}nav summary{cursor:pointer;list-style:none}nav details div{position:absolute;background:#f5f1e8;color:#203a35;padding:10px 16px;min-width:150px;box-shadow:0 4px 16px #0002}nav details a{display:block;color:#203a35;white-space:nowrap}.wrap{max-width:1180px;margin:auto;padding:56px 6vw}h1{font-size:clamp(2.2rem,5vw,4.8rem);line-height:1.15;margin:.2em 0;color:#d9b26f}h2{color:#7e4b31;margin-top:0}.lead{max-width:680px;font-size:1.15rem}.hero{background:#203a35;color:#f5f1e8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px}.tile{background:#fffaf0;border:1px solid #d8cdbb;padding:20px;min-height:150px}.wall .tile{background:linear-gradient(150deg,#dac9ab,#e9e0cf);min-height:170px;display:flex;flex-direction:column;justify-content:end}.meta{color:#8d6a45;font-size:.88rem;letter-spacing:.06em}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;background:#fffaf0}th,td{text-align:left;padding:12px;border-bottom:1px solid #d8cdbb}audio{width:100%;margin:12px 0}form{display:grid;gap:12px;max-width:680px}input,textarea,select,button{font:inherit;padding:11px;border:1px solid #b9ad9a;background:#fffaf0;color:#26352f}textarea{min-height:110px}button{background:#7e4b31;color:#fffaf0;cursor:pointer;border:0}footer{background:#d8cdbb;padding:24px 6vw}.tag{display:inline-block;padding:2px 8px;border:1px solid #b9ad9a;border-radius:2px;margin-right:6px;font-size:.8rem}
</style></head><body>
<header><nav><strong>古琴艺术专题</strong>{{range .Nav}}<details><summary>{{.Label}}</summary><div>{{range .Items}}<a href="{{.Href}}">{{.Label}}</a>{{end}}</div></details>{{end}}</nav></header>
<section class="hero"><div class="wrap"><p class="meta">一弦一意 · 山水有声</p><h1>听见山水<br>从一张琴开始</h1><p class="lead">从琴派、名曲、减字谱到传承故事，沿着古琴留下的声音与手艺，进入一段安静而丰厚的文化旅程。</p><a href="#pieces" style="color:#d9b26f">开始聆听 ↓</a></div></section>
<main>
<section class="wrap" id="intro"><p class="meta">01 / 琴派与地域</p><h2>琴声有来处</h2><div class="grid">{{range .Home.Schools}}<article class="tile"><p class="meta">{{.Region}} · {{.Period}}</p><h3>{{.Name}}</h3><p>{{.Description}}</p><small>传承线索：{{.Founder}}</small></article>{{end}}</div></section>
<section class="wrap wall" id="stories"><p class="meta">02 / 图片墙</p><h2>山水与琴人的身影</h2><div class="grid">{{range .Home.ImageWall}}<article class="tile"><p class="meta">{{.Kicker}}</p><h3>{{.Heading}}</h3><p>{{.Text}}</p></article>{{end}}</div></section>
<section class="wrap" id="pieces"><p class="meta">03 / 名曲目录</p><h2>让曲目成为入口</h2><div class="table-wrap"><table><thead><tr><th>曲名</th><th>传谱</th><th>气质</th><th>时长</th><th>本地占位音频</th></tr></thead><tbody>{{range .Home.Pieces}}<tr><td>{{.Title}}</td><td>{{.Composer}}</td><td><span class="tag">{{.Mood}}</span></td><td>{{.DurationLabel}}</td><td><audio controls preload="none" src="{{.AudioPath}}" aria-label="{{.Title}}"></audio></td></tr>{{end}}</tbody></table></div></section>
<section class="wrap" id="courtesy"><p class="meta">04 / 演奏礼仪</p><h2>先安其心，再落其指</h2><div class="grid">{{range .Home.Courtesy}}<article class="tile"><p class="meta">{{.DisplayOrder}}</p><h3>{{.Title}}</h3><p>{{.Content}}</p></article>{{end}}</div></section>
<section class="wrap" id="player"><p class="meta">05 / 体验表单</p><h2>留下你的听琴计划</h2><form method="post" action="/api/experience"><label>称呼<input required name="name" maxlength="80"></label><label>联系方式<input required name="contact" maxlength="120"></label><label>感兴趣的方向<select required name="interest"><option value="">请选择</option><option>名曲聆听</option><option>减字谱入门</option><option>斫琴与修琴</option><option>琴派故事</option></select></label><label>想说的话<textarea name="message" maxlength="1000"></textarea></label><button type="submit">提交体验</button></form></section>
</main><footer>古琴艺术专题 · 固定夹具演示服务 · 本地音频路径可替换为真实曲目</footer></body></html>`
